title: TotallyWholesome Wiki
description: Totally Wholesome is a module built with lewd functions in mind. Supports the use of leashes to drag around your pet, Lovense integration to have some fun, and PiShock for those certain punishments. This requires consent of both players, and for both to have the mod.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
